name: SQLibrary
version: 3.1
description: A library for ease of connection between a plugin and any database engine.

author: PatPeter
#authors: 
#website: 

main: lib.PatPeter.SQLibrary.SQLibrary
database: false
#depend: []

#commands:

#permissions: